$ErrorActionPreference = 'Stop'
$c = (Invoke-WebRequest -Uri 'https://flier3186.github.io/quiqu-xueyuan/index.html' -UseBasicParsing).Content
Write-Host "=== Final Deployment Verification ==="
Write-Host "size=$($c.Length)"
Write-Host "petCanvasAnim=$($c.Contains('petCanvasAnim'))"
Write-Host "LISTENING_DATA=$($c.Contains('LISTENING_DATA'))"
Write-Host "engSceneBanner=$($c.Contains('engSceneBanner'))"
Write-Host "achievementWall=$($c.Contains('achievementWall'))"
Write-Host "reviewReminder=$($c.Contains('reviewReminder'))"
Write-Host "serviceWorker=$($c.Contains('serviceWorker'))"
Write-Host "playEngSceneAudio=$($c.Contains('playEngSceneAudio'))"
Write-Host "renderListenExercise=$($c.Contains('renderListenExercise'))"
Write-Host "SpeakEngineV5=$($c.Contains('SpeakEngineV5'))"
Write-Host "SceneManager=$($c.Contains('SceneManager'))"
Write-Host "Achievements=$($c.Contains('Achievements'))"
